theme = "mytheme"

[editor]
bufferline = "multiple"
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
